# Here you can create Secrets for Formtion which will be passed on as Environment.

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
data:
  NUXT_DRIVE_UPLOAD_URL: {{ .Values.secret.nuxtDriveUploadUrl }}
  NUXT_DRIVE_DOWNLOAD_URL: {{ .Values.secret.nuxtDriveDownloadUrl }}
  NUXT_DRIVE_PASSWORD: {{ .Values.secret.nuxtDrivePassword }}