name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mattiamueggler
  IMAGE_TAG: latest
  GH_USERNAME: m-mattia-m

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file ./.docker/Dockerfile --tag $IMAGE_NAME --label $IMAGE_TAG
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Add tag to image
        run: docker tag $IMAGE_NAME ghcr.io/$GH_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - name: Push image to container-registry
        run: docker push ghcr.io/$GH_USERNAME/$IMAGE_NAME:$IMAGE_TAG