name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mattiamueggler
  IMAGE_TAG: latest
  GH_USERNAME: m-mattia-m

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM install
        run: npm install
      - name: NPM install nuxt
        run: npm install nuxt
      - name: NPM build
        run: npm run build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: |
          npm install
      - name: Install nuxt
        run: |
          npm install nuxt
      - name: Build
        run: |
          npm run build
      - name: Publish
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages